Part 1
SozonikOleg/js-assignments pull request #1
Opened 2019-02-20 10:34 UTC by SozonikOleg

Part-1

2019-02-20 13:10 UTC, RamanRudski requested changes

2019-02-20 13:10 UTC, RamanRudski commented on task/01-strings-tasks.js
> +  var input     = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
`var` устаревшее объявление переменной,  используй `let` `const`

2019-02-20 13:10 UTC, RamanRudski commented on task/01-strings-tasks.js
> +  var num=['A', '2', '3', '4', '5', '6', '7', '8', '9', '1', 'J', 'Q', 'K'];
неверное значение в массиве, вместо 1 должно быть 10.

2019-02-20 13:10 UTC, RamanRudski commented on task/01-strings-tasks.js
> +  return (typeof(value)==='string'||value instanceof String) ? true : false;
Тернарный оператор не обязателен , будет работать и так `typeof(value)==='string'||value instanceof String`

2019-02-20 13:10 UTC, Erromanr commented on task/02-numbers-tasks.js
> +  return 2 * 3.1415926535897931384626433832795 * radius;
`3.1415926535897931384626433832795` это значение есть в `Math`

2019-02-20 13:10 UTC, Erromanr commented on task/02-numbers-tasks.js
> +  return Math.acos((x1 * x2)+(y1 * y2))/Math.hypot(x1, y1) * Math.hypot(x2, y2);
` / ` раздели пробелами, для читаемости.

2019-02-20 13:10 UTC, Erromanr commented on task/02-numbers-tasks.js
> +  return +value.toString().split('').pop();
`pop()` в первую очередь нужен для удаления последнего элемента. Используй другое решение.

2019-02-20 13:10 UTC, Erromanr commented on task/02-numbers-tasks.js
> +  return Math.round(num / +(1+'0'.repeat(pow))) * +(1+'0'.repeat(pow));
`+(1+'0'.repeat(pow))` это не то решение, просто замени это на возведение 10-ки в степень `pow`.

2019-02-22 10:47 UTC, SozonikOleg commented on task/01-strings-tasks.js
> +  var input     = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
Пофиксил

2019-02-22 10:49 UTC, SozonikOleg commented on task/01-strings-tasks.js
> +  var num=['A', '2', '3', '4', '5', '6', '7', '8', '9', '1', 'J', 'Q', 'K'];
Пофиксил. Но там такая строка большая получилась(

2019-02-22 10:50 UTC, SozonikOleg commented on task/01-strings-tasks.js
> +  return (typeof(value)==='string'||value instanceof String) ? true : false;
Пофиксил

2019-02-22 10:50 UTC, SozonikOleg commented on task/02-numbers-tasks.js
> +  return 2 * 3.1415926535897931384626433832795 * radius;
Пофиксил

2019-02-22 10:50 UTC, SozonikOleg commented on task/02-numbers-tasks.js
> +  return Math.acos((x1 * x2)+(y1 * y2))/Math.hypot(x1, y1) * Math.hypot(x2, y2);
Пофиксил

2019-02-22 11:04 UTC, SozonikOleg commented on task/02-numbers-tasks.js
> +  return +value.toString().split('').pop();
Пофиксил с помощью slice:
+value.toString().slice(-1);

2019-02-22 12:08 UTC, SozonikOleg commented on task/02-numbers-tasks.js
> +  return Math.round(num / +(1+'0'.repeat(pow))) * +(1+'0'.repeat(pow));
Пофиксил

2019-02-22 14:32 UTC, RamanRudski requested changes

2019-02-22 14:32 UTC, Erromanr commented on task/03-date-tasks.js
>  }
`substr(11, 12)` это ок, но сейчас больше используют `slice()`

2019-02-22 14:32 UTC, Erromanr commented on task/03-date-tasks.js
>  }
В этом решении ты 3 раза вызываешь один метод метод `getUTCFullYear()`, объяви переменную и присвой ей значение `date.getUTCFullYear()`

2019-02-22 14:32 UTC, Erromanr commented on task/02-numbers-tasks.js
> +  return (value>def)?+value : def;
Это плохое решение, используй конструкции языка для более явной проверки. `typeof` `isNaN`

2019-02-27 14:20 UTC, SozonikOleg commented on task/03-date-tasks.js
>  }
Понял, буду использовать slice( ) в следующий раз.

2019-02-27 14:20 UTC, SozonikOleg commented on task/03-date-tasks.js
>  }
Пофиксил

2019-02-27 14:20 UTC, SozonikOleg commented on task/02-numbers-tasks.js
> +  return (value>def)?+value : def;
Пофиксил

2019-02-28 08:01 UTC, RamanRudski approved these changes

2019-02-28 08:02 UTC, merged