04 arrays tasks
SozonikOleg/js-assignments pull request #2
Opened 2019-02-27 14:39 UTC by SozonikOleg

2019-02-28 11:11 UTC, RamanRudski requested changes

2019-02-28 11:11 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  return arr.filter(item => typeof item === typeof '');
`typeof ' '` замени на `'string'`

2019-02-28 11:11 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  return arr.map((item, i) => item.length);
Ты не используешь индекс, следовательно он тебе не нужен в `(item, i) =>`, убери `i`

2019-02-28 11:11 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  return arr.slice(arr.length - n);
Достаточно использовать `arr.slice(- n)`, в данном случае `slice` будет возвращать массив отчитывая от последнего элемента массива.

2019-02-28 11:11 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  return arr.reduce((a, x, i) => [...a, a.length > 0 ? x + a[i-1] : x], []);
Здесь все хорошо, но не называй параметры `reduce` одним символом, семантически сложно будет читать в коде.
Использующий  например  `arr.reduce((acc ,curr, index)`. 
Задача не нуждается в исправлении, комментарий оставлен как пожелание на будущее.

2019-02-28 11:11 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  return arr.reduce((n, val) => n + (val === item), 0);
В данном случае более логично использовать `filter()` а не `reduce()`

2019-02-28 11:11 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  return arr.slice(',');
Когда тебе нужно преобразовать массив элементов в строку с каким либо "разделителем" используй `join()`

2019-02-28 11:11 UTC, RamanRudski commented on task/04-arrays-tasks.js
> +  });
Это плохое решение)) За такое количество `if` на проектах бьют по рукам)
Обрати внимание на `String.localeCompare`, и переделай задачу .

2019-02-28 20:44 UTC, SozonikOleg commented on task/04-arrays-tasks.js
> +  return arr.filter(item => typeof item === typeof '');
Пофиксил

2019-02-28 20:45 UTC, SozonikOleg commented on task/04-arrays-tasks.js
> +  return arr.map((item, i) => item.length);
Пофиксил

2019-02-28 20:46 UTC, SozonikOleg commented on task/04-arrays-tasks.js
> +  return arr.slice(arr.length - n);
Пофиксил

2019-02-28 20:52 UTC, SozonikOleg commented on task/04-arrays-tasks.js
> +  return arr.reduce((a, x, i) => [...a, a.length > 0 ? x + a[i-1] : x], []);
Пофиксил читаемость

2019-02-28 21:06 UTC, SozonikOleg commented on task/04-arrays-tasks.js
> +  return arr.reduce((n, val) => n + (val === item), 0);
Пофиксил

2019-02-28 21:08 UTC, SozonikOleg commented on task/04-arrays-tasks.js
> +  return arr.slice(',');
Пофиксил

2019-02-28 22:50 UTC, SozonikOleg commented on task/04-arrays-tasks.js
> +  });
Пофиксил

2019-03-01 07:16 UTC, RamanRudski approved these changes

2019-03-01 07:49 UTC, merged