06 conditions n loops tasks
SozonikOleg/js-assignments pull request #4
Opened 2019-03-06 14:06 UTC by SozonikOleg

2019-03-12 11:46 UTC, RamanRudski requested changes

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +  else{
Тебе не нужен `else`, достаточно обычного `return true` , т.к. если условие не пройдет функция выполнит `return`.

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +  for (var i = 0; i < str.length; i++) {
используй `let`

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +    var c = str.charAt(i);
плохое название переменной, семантически непонятно что это такое.

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +      return c; }
`}` закрывающийся скобка должна быть на следующей строке.

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +  const resalt = (a < b) ? a + ', ' + b  : b + ', ' + a;
Используй шаблонные литералы, решение будет такого вида``${(a < b) ? `${a}, ${b}` : `${b}, ${a}`}``

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +  const value = (isStartIncluded && isEndIncluded) ? '[' + resalt + ']' :
Очень много условий.  Сделай 2 условия для определения с какой скобки начинать и какой заканчивать. `const openingBracket = isStartIncluded ? : ' [ ' + ' { '` тоже самое для закрывающей. А затем верни сумму `openingBracket + result + closingBracket `

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +  var digit, digits, flag, sum, _i, _len;
не используй `var`.

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +  for (_i = 0, _len = digits.length; _i < _len; _i++) {
Это убираем и делаем `ccn.toString().split('').reverse().forEach((value, index) =>`

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +  const z = num.toString().split('').reduce((sum, item) => sum += Number(item), 0);//eslint-disable-line
`z` плохое название. Название переменных и функций должны раскрывать зачем она нужна.

2019-03-12 11:46 UTC, RamanRudski commented on task/06-conditions-n-loops-tasks.js
> +  const resalt = (date<=45*sec) ? 'a few seconds ago' :
Используй `switch` это случай когда нужно использовать его  . И больше никогда не пиши такое количество условий ))

2019-03-13 20:51 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +  else{
Пофиксил.

2019-03-13 20:51 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +  for (var i = 0; i < str.length; i++) {
Пофиксил

2019-03-13 20:56 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +    var c = str.charAt(i);
Пофиксил

2019-03-13 21:02 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +  const resalt = (a < b) ? a + ', ' + b  : b + ', ' + a;
Пофиксил

2019-03-13 21:08 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +  var digit, digits, flag, sum, _i, _len;
Пофиксил

2019-03-13 21:12 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +  const z = num.toString().split('').reduce((sum, item) => sum += Number(item), 0);//eslint-disable-line
Пофиксил

2019-03-20 07:33 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +      return c; }
пофиксил

2019-03-20 07:43 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +  const value = (isStartIncluded && isEndIncluded) ? '[' + resalt + ']' :
Пофиксил.

2019-03-20 09:07 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +  for (_i = 0, _len = digits.length; _i < _len; _i++) {
Пофиксил

2019-03-20 09:42 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +  const resalt = (date<=45*sec) ? 'a few seconds ago' :
Пофиксил

2019-03-20 09:43 UTC, SozonikOleg commented on task/06-conditions-n-loops-tasks.js
> +  const resalt = (date<=45*sec) ? 'a few seconds ago' :
Пофиксил

2019-03-20 10:22 UTC, RamanRudski approved these changes

2019-03-20 10:24 UTC, merged