09 functions n closures tasks
SozonikOleg/js-assignments pull request #6
Opened 2019-03-20 10:33 UTC by SozonikOleg

2019-03-21 16:01 UTC, RamanRudski requested changes

2019-03-21 16:01 UTC, Erromanr commented on task/09-functions-n-closures-tasks.js
> +  this.a = func();
Здесь не нужно использовать контекст, достаточно присвоить переменной.

2019-03-26 09:39 UTC, SozonikOleg commented on task/09-functions-n-closures-tasks.js
> +  this.a = func();
пофиксил

2019-03-26 11:04 UTC, RamanRudski approved these changes

2019-03-26 11:05 UTC, merged